// Generated CODE, PLEASE EDIT WITH CARE 



var opACC0=0;

var opACC1=1;

var opACC2=2;

var opACC3=3;

var opACC4=4;

var opACC5=5;

var opACC6=6;

var opACC7=7;

var opACC=8;

var opPUSH=9;

var opPUSHACC0=10;

var opPUSHACC1=11;

var opPUSHACC2=12;

var opPUSHACC3=13;

var opPUSHACC4=14;

var opPUSHACC5=15;

var opPUSHACC6=16;

var opPUSHACC7=17;

var opPUSHACC=18;

var opPOP=19;

var opASSIGN=20;

var opENVACC1=21;

var opENVACC2=22;

var opENVACC3=23;

var opENVACC4=24;

var opENVACC=25;

var opPUSHENVACC1=26;

var opPUSHENVACC2=27;

var opPUSHENVACC3=28;

var opPUSHENVACC4=29;

var opPUSHENVACC=30;

var opPUSH_RETADDR=31;

var opAPPLY=32;

var opAPPLY1=33;

var opAPPLY2=34;

var opAPPLY3=35;

var opAPPTERM=36;

var opAPPTERM1=37;

var opAPPTERM2=38;

var opAPPTERM3=39;

var opRETURN=40;

var opRESTART=41;

var opGRAB=42;

var opCLOSURE=43;

var opCLOSUREREC=44;

var opOFFSETCLOSUREM2=45;

var opOFFSETCLOSURE0=46;

var opOFFSETCLOSURE2=47;

var opOFFSETCLOSURE=48;

var opPUSHOFFSETCLOSUREM2=49;

var opPUSHOFFSETCLOSURE0=50;

var opPUSHOFFSETCLOSURE2=51;

var opPUSHOFFSETCLOSURE=52;

var opGETGLOBAL=53;

var opPUSHGETGLOBAL=54;

var opGETGLOBALFIELD=55;

var opPUSHGETGLOBALFIELD=56;

var opSETGLOBAL=57;

var opATOM0=58;

var opATOM=59;

var opPUSHATOM0=60;

var opPUSHATOM=61;

var opMAKEBLOCK=62;

var opMAKEBLOCK1=63;

var opMAKEBLOCK2=64;

var opMAKEBLOCK3=65;

var opMAKEFLOATBLOCK=66;

var opGETFIELD0=67;

var opGETFIELD1=68;

var opGETFIELD2=69;

var opGETFIELD3=70;

var opGETFIELD=71;

var opGETFLOATFIELD=72;

var opSETFIELD0=73;

var opSETFIELD1=74;

var opSETFIELD2=75;

var opSETFIELD3=76;

var opSETFIELD=77;

var opSETFLOATFIELD=78;

var opVECTLENGTH=79;

var opGETVECTITEM=80;

var opSETVECTITEM=81;

var opGETSTRINGCHAR=82;

var opSETSTRINGCHAR=83;

var opBRANCH=84;

var opBRANCHIF=85;

var opBRANCHIFNOT=86;

var opSWITCH=87;

var opBOOLNOT=88;

var opPUSHTRAP=89;

var opPOPTRAP=90;

var opRAISE=91;

var opCHECK_SIGNALS=92;

var opC_CALL1=93;

var opC_CALL2=94;

var opC_CALL3=95;

var opC_CALL4=96;

var opC_CALL5=97;

var opC_CALLN=98;

var opCONST0=99;

var opCONST1=100;

var opCONST2=101;

var opCONST3=102;

var opCONSTINT=103;

var opPUSHCONST0=104;

var opPUSHCONST1=105;

var opPUSHCONST2=106;

var opPUSHCONST3=107;

var opPUSHCONSTINT=108;

var opNEGINT=109;

var opADDINT=110;

var opSUBINT=111;

var opMULINT=112;

var opDIVINT=113;

var opMODINT=114;

var opANDINT=115;

var opORINT=116;

var opXORINT=117;

var opLSLINT=118;

var opLSRINT=119;

var opASRINT=120;

var opEQ=121;

var opNEQ=122;

var opLTINT=123;

var opLEINT=124;

var opGTINT=125;

var opGEINT=126;

var opOFFSETINT=127;

var opOFFSETREF=128;

var opISINT=129;

var opGETMETHOD=130;

var opBEQ=131;

var opBNEQ=132;

var opBLTINT=133;

var opBLEINT=134;

var opBGTINT=135;

var opBGEINT=136;

var opULTINT=137;

var opUGEINT=138;

var opBULTINT=139;

var opBUGEINT=140;

var opGETPUBMET=141;

var opGETDYNMET=142;

var opSTOP=143;

var opEVENT=144;

var opBREAK=145;

var opRERAISE=146;

var opRAISE_NOTRACE=147;

module["exports"]=
{"opACC0":opACC0,
 "opACC1":opACC1,
 "opACC2":opACC2,
 "opACC3":opACC3,
 "opACC4":opACC4,
 "opACC5":opACC5,
 "opACC6":opACC6,
 "opACC7":opACC7,
 "opACC":opACC,
 "opPUSH":opPUSH,
 "opPUSHACC0":opPUSHACC0,
 "opPUSHACC1":opPUSHACC1,
 "opPUSHACC2":opPUSHACC2,
 "opPUSHACC3":opPUSHACC3,
 "opPUSHACC4":opPUSHACC4,
 "opPUSHACC5":opPUSHACC5,
 "opPUSHACC6":opPUSHACC6,
 "opPUSHACC7":opPUSHACC7,
 "opPUSHACC":opPUSHACC,
 "opPOP":opPOP,
 "opASSIGN":opASSIGN,
 "opENVACC1":opENVACC1,
 "opENVACC2":opENVACC2,
 "opENVACC3":opENVACC3,
 "opENVACC4":opENVACC4,
 "opENVACC":opENVACC,
 "opPUSHENVACC1":opPUSHENVACC1,
 "opPUSHENVACC2":opPUSHENVACC2,
 "opPUSHENVACC3":opPUSHENVACC3,
 "opPUSHENVACC4":opPUSHENVACC4,
 "opPUSHENVACC":opPUSHENVACC,
 "opPUSH_RETADDR":opPUSH_RETADDR,
 "opAPPLY":opAPPLY,
 "opAPPLY1":opAPPLY1,
 "opAPPLY2":opAPPLY2,
 "opAPPLY3":opAPPLY3,
 "opAPPTERM":opAPPTERM,
 "opAPPTERM1":opAPPTERM1,
 "opAPPTERM2":opAPPTERM2,
 "opAPPTERM3":opAPPTERM3,
 "opRETURN":opRETURN,
 "opRESTART":opRESTART,
 "opGRAB":opGRAB,
 "opCLOSURE":opCLOSURE,
 "opCLOSUREREC":opCLOSUREREC,
 "opOFFSETCLOSUREM2":opOFFSETCLOSUREM2,
 "opOFFSETCLOSURE0":opOFFSETCLOSURE0,
 "opOFFSETCLOSURE2":opOFFSETCLOSURE2,
 "opOFFSETCLOSURE":opOFFSETCLOSURE,
 "opPUSHOFFSETCLOSUREM2":opPUSHOFFSETCLOSUREM2,
 "opPUSHOFFSETCLOSURE0":opPUSHOFFSETCLOSURE0,
 "opPUSHOFFSETCLOSURE2":opPUSHOFFSETCLOSURE2,
 "opPUSHOFFSETCLOSURE":opPUSHOFFSETCLOSURE,
 "opGETGLOBAL":opGETGLOBAL,
 "opPUSHGETGLOBAL":opPUSHGETGLOBAL,
 "opGETGLOBALFIELD":opGETGLOBALFIELD,
 "opPUSHGETGLOBALFIELD":opPUSHGETGLOBALFIELD,
 "opSETGLOBAL":opSETGLOBAL,
 "opATOM0":opATOM0,
 "opATOM":opATOM,
 "opPUSHATOM0":opPUSHATOM0,
 "opPUSHATOM":opPUSHATOM,
 "opMAKEBLOCK":opMAKEBLOCK,
 "opMAKEBLOCK1":opMAKEBLOCK1,
 "opMAKEBLOCK2":opMAKEBLOCK2,
 "opMAKEBLOCK3":opMAKEBLOCK3,
 "opMAKEFLOATBLOCK":opMAKEFLOATBLOCK,
 "opGETFIELD0":opGETFIELD0,
 "opGETFIELD1":opGETFIELD1,
 "opGETFIELD2":opGETFIELD2,
 "opGETFIELD3":opGETFIELD3,
 "opGETFIELD":opGETFIELD,
 "opGETFLOATFIELD":opGETFLOATFIELD,
 "opSETFIELD0":opSETFIELD0,
 "opSETFIELD1":opSETFIELD1,
 "opSETFIELD2":opSETFIELD2,
 "opSETFIELD3":opSETFIELD3,
 "opSETFIELD":opSETFIELD,
 "opSETFLOATFIELD":opSETFLOATFIELD,
 "opVECTLENGTH":opVECTLENGTH,
 "opGETVECTITEM":opGETVECTITEM,
 "opSETVECTITEM":opSETVECTITEM,
 "opGETSTRINGCHAR":opGETSTRINGCHAR,
 "opSETSTRINGCHAR":opSETSTRINGCHAR,
 "opBRANCH":opBRANCH,
 "opBRANCHIF":opBRANCHIF,
 "opBRANCHIFNOT":opBRANCHIFNOT,
 "opSWITCH":opSWITCH,
 "opBOOLNOT":opBOOLNOT,
 "opPUSHTRAP":opPUSHTRAP,
 "opPOPTRAP":opPOPTRAP,
 "opRAISE":opRAISE,
 "opCHECK_SIGNALS":opCHECK_SIGNALS,
 "opC_CALL1":opC_CALL1,
 "opC_CALL2":opC_CALL2,
 "opC_CALL3":opC_CALL3,
 "opC_CALL4":opC_CALL4,
 "opC_CALL5":opC_CALL5,
 "opC_CALLN":opC_CALLN,
 "opCONST0":opCONST0,
 "opCONST1":opCONST1,
 "opCONST2":opCONST2,
 "opCONST3":opCONST3,
 "opCONSTINT":opCONSTINT,
 "opPUSHCONST0":opPUSHCONST0,
 "opPUSHCONST1":opPUSHCONST1,
 "opPUSHCONST2":opPUSHCONST2,
 "opPUSHCONST3":opPUSHCONST3,
 "opPUSHCONSTINT":opPUSHCONSTINT,
 "opNEGINT":opNEGINT,
 "opADDINT":opADDINT,
 "opSUBINT":opSUBINT,
 "opMULINT":opMULINT,
 "opDIVINT":opDIVINT,
 "opMODINT":opMODINT,
 "opANDINT":opANDINT,
 "opORINT":opORINT,
 "opXORINT":opXORINT,
 "opLSLINT":opLSLINT,
 "opLSRINT":opLSRINT,
 "opASRINT":opASRINT,
 "opEQ":opEQ,
 "opNEQ":opNEQ,
 "opLTINT":opLTINT,
 "opLEINT":opLEINT,
 "opGTINT":opGTINT,
 "opGEINT":opGEINT,
 "opOFFSETINT":opOFFSETINT,
 "opOFFSETREF":opOFFSETREF,
 "opISINT":opISINT,
 "opGETMETHOD":opGETMETHOD,
 "opBEQ":opBEQ,
 "opBNEQ":opBNEQ,
 "opBLTINT":opBLTINT,
 "opBLEINT":opBLEINT,
 "opBGTINT":opBGTINT,
 "opBGEINT":opBGEINT,
 "opULTINT":opULTINT,
 "opUGEINT":opUGEINT,
 "opBULTINT":opBULTINT,
 "opBUGEINT":opBUGEINT,
 "opGETPUBMET":opGETPUBMET,
 "opGETDYNMET":opGETDYNMET,
 "opSTOP":opSTOP,
 "opEVENT":opEVENT,
 "opBREAK":opBREAK,
 "opRERAISE":opRERAISE,
 "opRAISE_NOTRACE":opRAISE_NOTRACE};

